###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "login": "marian123",
  "legoSets": [2,3]
}

###
PATCH http://localhost:8080/users/5
Content-Type: application/json

{
  "login": "user123",
  "legoSets": [2,3]
}

###
DELETE http://localhost:8080/users/8

###
GET http://localhost:8080/users/6
